volumes:
  llmprox_local_postgres_data: {}
  llmprox_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: llmprox_local_django
    container_name: llmprox_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.env
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: llmprox_production_postgres
    container_name: llmprox_local_postgres
    ports:
      - '5432:5432'
    volumes:
      - llmprox_local_postgres_data:/var/lib/postgresql/data
      - llmprox_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.env
